# Generated by Django 5.2.16 on 2026-08-03 20:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('q_title', models.CharField(max_length=100)),
                ('q_no', models.IntegerField()),
                ('date_published', models.DateField(default=datetime.datetime.now)),
                ('q_content', models.CharField(max_length=60000)),
                ('q_tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case', models.CharField(max_length=1000000009)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.questions')),
            ],
        ),
    ]
