# Generated by Django 5.2.16 on 2026-08-05 19:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('q_no', models.IntegerField(unique=True)),
                ('q_title', models.CharField(max_length=100)),
                ('q_description', models.TextField()),
                ('q_input_format', models.TextField()),
                ('q_output_format', models.TextField()),
                ('q_sample_io', models.TextField()),
                ('q_tag', models.CharField(max_length=30)),
                ('q_difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('date_published', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('lang', models.CharField(max_length=20)),
                ('verdict', models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('MLE', 'Memory Limit Exceeded')], default='WA', max_length=3)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problembank.problems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case', models.TextField()),
                ('expected_output', models.TextField()),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problembank.problems')),
            ],
        ),
    ]
