# Generated by Django 5.2.16 on 2026-08-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problembank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='test_case_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testcases',
            name='visiblity',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], default='PRIVATE', max_length=20),
        ),
    ]
