# Generated by Django 5.2.16 on 2026-08-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=14)),
                ('content', models.TextField()),
            ],
        ),
    ]
